<?php

/*
 * This file is part of lcoy/cipher.
 *
 * (c) Lcoy
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Lcoy\Cipher\Api\Controller;

use DOMDocument;
use DOMXPath;
use Flarum\Formatter\Formatter;
use Flarum\Http\RequestUtil;
use Flarum\Locale\TranslatorInterface;
use Flarum\Post\CommentPost;
use Flarum\Settings\SettingsRepositoryInterface;
use Illuminate\Contracts\Cache\Repository as Cache;
use Laminas\Diactoros\Response\JsonResponse;
use Lcoy\Cipher\Conditions;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

class UnlockController implements RequestHandlerInterface
{
    private const MAX_ATTEMPTS = 10;
    private const WINDOW_SECONDS = 600;

    public function __construct(
        protected Formatter $formatter,
        protected SettingsRepositoryInterface $settings,
        protected TranslatorInterface $translator,
        protected Cache $cache,
        protected Conditions $conditions
    ) {
    }

    /**
     * POST /api/resource/unlock
     *
     * Body: { postId: number, bbcodeIndex: string, password: string }
     *
     * - 200 { success: true, html: "<...>" } on success.
     * - 403 { success: false, error: "..." } on a wrong password or an unmet
     *   visibility requirement.
     */
    public function handle(ServerRequestInterface $request): ResponseInterface
    {
        $actor = RequestUtil::getActor($request);
        $body = (array) $request->getParsedBody();

        $postId = (int) ($body['postId'] ?? 0);
        $cipherId = (string) ($body['bbcodeIndex'] ?? '');
        $password = (string) ($body['password'] ?? '');

        if ($postId <= 0 || $cipherId === '' || $password === '') {
            return $this->error(400, $this->translator->trans('lcoy-cipher.forum.invalid_request'));
        }

        // bcrypt only considers the first 72 bytes anyway; cap the input so a
        // megabyte-long "password" can't be used to make the server do heavy
        // hashing work on a cheap request.
        if (strlen($password) > 255) {
            return $this->error(400, $this->translator->trans('lcoy-cipher.forum.invalid_request'));
        }

        // Only accept ids generated by ProtectedFilter.
        if (! preg_match('/^cipher_[a-f0-9]{16}$/', $cipherId)) {
            return $this->error(404, $this->translator->trans('lcoy-cipher.forum.post_not_found'));
        }

        $post = CommentPost::find($postId);

        if (! $post || ! $post->isVisibleTo($actor)) {
            return $this->error(404, $this->translator->trans('lcoy-cipher.forum.post_not_found'));
        }

        $block = $this->findBlock($post, $cipherId);

        if ($block === null) {
            return $this->error(404, $this->translator->trans('lcoy-cipher.forum.post_not_found'));
        }

        // Admins never need a password.
        if ($actor->isAdmin()) {
            return $this->success($post, $block, $request);
        }

        // Admins may disable unlocking for guests.
        if ($actor->isGuest() && ! (bool) $this->settings->get('lcoy-cipher.allow_guest_unlock', true)) {
            return $this->error(403, $this->translator->trans('lcoy-cipher.forum.unlock_disabled'));
        }

        // Time-gated content cannot be unlocked before its scheduled time.
        if (($target = $this->conditions->timeTarget($block)) !== null && time() < $target) {
            return $this->error(403, $this->translator->trans('lcoy-cipher.forum.unlock_time'));
        }

        // Basic brute-force protection: per post + IP failed-attempt counter.
        $attemptKey = 'lcoy-cipher.attempts.'.sha1($postId.'|'.$request->getAttribute('ipAddress', '0'));

        if ((int) $this->cache->get($attemptKey, 0) >= self::MAX_ATTEMPTS) {
            return $this->error(429, $this->translator->trans('lcoy-cipher.forum.too_many_attempts'));
        }

        if (! password_verify($password, $block['hash'])) {
            $this->cache->put($attemptKey, (int) $this->cache->get($attemptKey, 0) + 1, self::WINDOW_SECONDS);

            return $this->error(403, $this->translator->trans('lcoy-cipher.forum.wrong_password'));
        }

        // Even with the correct password, visibility conditions must be met.
        $unmet = $this->conditions->unmet($block, $post, $actor);

        if ($unmet !== []) {
            return $this->error(403, $this->unlockRequirementMessage($unmet[0], $block));
        }

        $this->cache->forget($attemptKey);

        return $this->success($post, $block, $request);
    }

    /**
     * Find a protected block in the post's parsed XML and extract its password
     * hash, inner content and visibility condition attributes.
     *
     * @return array{hash: string, inner: string, like: string, reply: string, follow: string, minlikes: string, time: string}|null
     */
    protected function findBlock(CommentPost $post, string $cipherId): ?array
    {
        $xml = $post->getParsedContentAttribute();

        if (! $xml || ! str_contains($xml, '<PROTECTED')) {
            return null;
        }

        $dom = new DOMDocument;
        $dom->loadXML('<cipher-root>'.$xml.'</cipher-root>', LIBXML_NONET | LIBXML_COMPACT);

        $xpath = new DOMXPath($dom);
        $nodes = $xpath->query('//PROTECTED[@id = "'.$cipherId.'"]');

        if (! $nodes || $nodes->length === 0) {
            return null;
        }

        $node = $nodes->item(0);

        $hash = $node->getAttribute('password');
        if ($hash === '') {
            // Legacy block parsed before the default-password feature: fall back
            // to the configured default password so the author's empty
            // `password=""` still unlocks.
            $hash = password_hash($this->defaultPassword(), PASSWORD_DEFAULT);
        }

        $inner = '';
        foreach ($node->childNodes as $child) {
            $inner .= $dom->saveXML($child);
        }

        $block = ['hash' => $hash, 'inner' => $inner];

        // s9e lowercases attribute names, so read every attribute with its
        // lowercase key.
        foreach (['like', 'reply', 'follow', 'followdiscussion', 'minlikes', 'time'] as $key) {
            $block[$key] = $node->hasAttribute($key) ? $node->getAttribute($key) : '';
        }

        return $block;
    }

    protected function unlockRequirementMessage(string $key, array $block): string
    {
        return match ($key) {
            'time' => $this->translator->trans('lcoy-cipher.forum.unlock_time'),
            'like' => $this->translator->trans('lcoy-cipher.forum.unlock_like'),
            'reply' => $this->translator->trans('lcoy-cipher.forum.unlock_reply'),
            'follow' => $this->translator->trans('lcoy-cipher.forum.unlock_follow'),
            'followDiscussion' => $this->translator->trans('lcoy-cipher.forum.unlock_follow_discussion'),
            'minlikes' => $this->translator->trans('lcoy-cipher.forum.unlock_minlikes', [
                'count' => (int) ($block['minlikes'] ?? 0),
            ]),
            default => $this->translator->trans('lcoy-cipher.forum.unlock_error'),
        };
    }

    protected function defaultPassword(): string
    {
        $default = (string) $this->settings->get('lcoy-cipher.default_password', '');

        return $default === '' ? 'cipher' : $default;
    }

    /**
     * Render the inner content of a protected block back to HTML.
     *
     * The s9e renderer only ever outputs configured tags with escaped
     * attributes/text, so the returned HTML is safe to insert into the page.
     */
    protected function success(CommentPost $post, array $block, ServerRequestInterface $request): JsonResponse
    {
        // Nested [protected] blocks inside the fragment are re-gated by the
        // RenderContent render hook (it runs on every Formatter render), so a
        // block unlocked by its outer password never exposes nested content.
        $html = $this->formatter->render('<r>'.$block['inner'].'</r>', $post, $request);

        return new JsonResponse(['success' => true, 'html' => $html]);
    }

    protected function error(int $status, string $message): JsonResponse
    {
        return new JsonResponse(['success' => false, 'error' => $message], $status);
    }
}
